### ISSUE TITLE
hotspot3d search question

### ISSUE THREAD

**Issue by statindfinecon** [ding-lab/hotspot3d#20]
Hello,
I used my maf file to run "hotspot3d search" ,and 
my cmd line:

~/perl5/bin/hotspot3d search --maf-file my.maf --drugport-file=drugport_results  --p-value-cutoff 0.05 --3d-distance-cutoff 10 --transcript-id-header Transcript_ID --amino-acid-header HGVSp_Short --prep-dir preprocessing_dir/ 

But the output :
......
Argument "208B" isn't numeric in addition (+) at /home/perl5/lib/perl5/TGI/Mutpro/Main/Proximiy.pm line 691, <GEN19> line 2605.
Argument "208B" isn't numeric in addition (+) at /home/perl5/lib/perl5/TGI/Mutpro/Main/Proximiy.pm line 691, <GEN19> line 2606.
searching done...
Creating 3D_Proximity.pairwise
Creating 3D_Proximity.cosmic
Creating 3D_Proximity.roi
**Could not open drug target output file**

Could you tell me how to solve this problem?   
(I have tried running hotspot3d correctly for two weeks.)
Thanks.

**Comment by AdamDS** [comment]
Thanks, @statindfinecon. To better help you, could you tell us what version of HotSpot3D you're using? Also, did you produce your own preprocessing data or did you download files from Synapse (if downloaded, what was the download date)?

**Comment by statindfinecon** [comment]
Thanks for your reply.

First, I tried HotSpot3D v0.6.0 and downloaded data from syn9704835 and syn9701918  (2017/8/15).
Run the steps from "drugport" --> "uppro" --> preprocessing steps 2a-2f. 
When I run "hotspot3d search",it shows "Could not open drug target output file".

So I update HotSpot3D (v1.7.3), and run the steps ("uppro"-->"prep").
It also shows "Could not open drug target output file" from the "search" step.

**Comment by liruilin7086** [comment]
Hello,
I also used a small demo file( just extract gene SMAD2 from demo.maf) to run "hotspot3d search", and my command line : 
hotspot3d search --maf-file small.demo.maf --prep-dir preprocessing_dir --3d-distance-cutoff 10 --drugport-file preprocessing_dir/drugport.201701.results 1>demo.search_test1.out 2>demo.search_test1.err

Here, I have downloaded all the prioritization files(October 2017), and the hotspot3d test version is  V1.8.1


**But demo.search_test1.err shows that:**
**Could not open drug target output file**

demo.search_test1.out shows that : 
=====Parameters=====
 p-value-cutoff        = 1
 3d-distance-cutoff    = 10
 skip-silent           = 0
 missense-only         = 0
 linear-cutoff         = 0
====================
......
searching...
searching done...
Creating 3D_Proximity.pairwise
Creating 3D_Proximity.cosmic
Creating 3D_Proximity.roi

Could you tell me how to solve this problem?
Thanks.

**Comment by amilacsw** [comment]
Thanks @liruilin7086 for bringing this issue up to our attention. We are aware about this bug, and working towards to fix it as soon as possible. We will get back to you once we have fixed it.

**Comment by yuanhe2017** [comment]
Hello,
I used the demo file (demo.maf ) to run "hotspot3d search" and met a similar problem, and
my cmd line:

hotspot3d search --maf-file=demo.maf --prep-dir=../../prep_dir/ --output-prefix=demo_3D_Proximity  --drugport-file=../../prep_dir/drugport.201701.results

The output:

searching...
searching done...
Creating demo_3D_Proximity.pairwise
Creating demo_3D_Proximity.cosmic
Creating demo_3D_Proximity.roi
Could not open drug target output file

I also downloaded all the prioritization files from Synapse and the hotspot3d test version is V1.7.3.

Could you tell me how to solve this problem?
Thanks.

**Comment by amilacsw** [comment]
Hi @yuanhe2017, @liruilin7086 and @statindfinecon, 

Thank you again for contacting us. We have fixed the bugs involved in file opening in HotSpot3D Preprocess. We have tested the fix in several of our perl environments. However, please let us know if they still do not work in your specific perl environment. Latest bug fixes can be found in version 1.8.2.       

Thank you!
Amila

**Comment by yuanhe2017** [comment]
Hi @amilacsw,
Thank you for  your reply.

I updated HotSpot3D from V1.7.3 to V1.8.2 and used demo.maf to run "hotspot3d search" again.   My HotSpot3d worked well, and 
my cmd line:

hotspot3d search --maf-file=demo.maf --prep-dir=../../Softwares/hotspot3d/prep_dir/ --output-prefix=demo_3D_Proximity  --drugport-file=../../Softwares/hotspot3d/prep_dir/drugport.201701.results

The output:

searching...
searching done...
Creating demo_3D_Proximity.pairwise
Creating demo_3D_Proximity.cosmic
Creating demo_3D_Proximity.roi
Creating demo_3D_Proximity.drugs.target.clean
Creating demo_3D_Proximity.drugs.nontarget.clean


##################################################
total mutations: 2309
expected mutations: 690
unexpected format mutations: 0
mutations with matched uniprot: 400
total transcripts with valid uniprot sequences : 16156
total transcripts in maf : 44
total mutations to be analyzed:  16156
total uniprots involved: 3


##################################################

Thank you

**Comment by AdamDS** [comment]
Thanks for the update. I'll mark this as closed.
