### ISSUE TITLE
prioritization.tar.gz (syn9704853) file missing in synapse

### ISSUE THREAD

**Issue by gpcr** [ding-lab/hotspot3d#21]
prioritization.tar.gz (syn9704853) not found . is there a new file to look for? 
Thanks

**Comment by shanshenbing** [comment]
Hello, Can you provide prioritization.tar.gz (syn9704853)? It is much more convent for users to download one file from synapse. And files in syn9705109 have both compressed gz file and uncompressed file, so I have to download them both when I use  synapserutils::syncFromSynapse(' syn9705109 ') .  Actully, the gz file is much smaller than the uncompressed files, I think you may use two dir to store the gz file and uncompressed files separately and download gz files only can save much time. I have struggled with this issue for several days and the download is fair with uncertain reason.
 
Hope your advice!
