### ISSUE TITLE
Adding a runnable demo 

### ISSUE THREAD

**Issue by zhilongjia** [ding-lab/hotspot3d#3]
Please add a runnable demo including an example data to show how to use hotspot3d. Thank you.

**Comment by AdamDS** [comment]
Thank you for the suggestion. I will see about putting together a demo.

**Comment by AdamDS** [comment]
I have added a demo. Follow the Demo/README_demo to see notes on how to run HotSpot3D.

**Comment by AdamDS** [comment]
Have received a confirmed demo run with success. Closing this issue.
